### ISSUE TITLE
hey selfless retard

### ISSUE THREAD

**Issue by CUKESIM** [ozzt-archive/ourblox#3]
why dont you go do something else instead of making revivals, your not gonna accomplish anything at all because you already know nobody is gonna join this shit revival after what you did to me and alice.

xoxo cukesim

**Comment by CUKESIM** [comment]
also fyi dshoe got on doxbin by carrot

carrot if your reading this i unbanned you from my server

**Comment by CUKESIM** [comment]
(someone said it was carrot)

**Comment by lighterlightbulb** [comment]
🥴

**Comment by ozzt** [comment]
This project has been unmaintained for over a year. Sorry for any inconvenience.
